#name: API VET CLINIC CD
#on:
#  workflow_run:
#    workflows: ["API VET CLINIC CI"]
#    types:
#      - completed

#jobs:

#  build:

#    runs-on: self-hosted

#    steps:
#    - name: enter super user
#      run: sudo su
#    - name: pull docker image
#      run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/api-vet-clinic:latest
#    - name: delete old docker container
#      run: sudo docker rm -f api-vet-clinic-container || true
#    - name: run docker container
#      run: sudo docker run -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_REGION=$AWS_REGION -e PORT=$PORT -e COLLECTION_PETS=$COLLECTION_PETS -e COLLECTION_VETERINARIANS=$COLLECTION_VETERINARIANS -d -p 8080:8080 --name api-vet-clinic-container ${{ secrets.DOCKERHUB_USERNAME }}/api-vet-clinic
