name: API VET CLINIC CI
on: [push]
jobs:
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup NodeJS
              uses: actions/setup-node@v2
              with:
                node-version: 18
            - name: Install
              shell: bash
              run: npm install
            - name: Run unit tests
              shell: bash
              run: npm run test
